server:
  port: 8080

spring:
  datasource:
    name: test
    url: jdbc:mysql://localhost:3306/real
    username: root
    password: 123456
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
  redis:
    database: 0
    host: 180.76.176.197
    port: 6381
    timeout: 3000
    password: shenwei
    pool:
      # 连接池最大连接数（使用负值表示没有限制）
      max-active: 8
      # 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
      # 连接池中的最大空闲连接
      max-idle: 8
      # 连接池中的最小空闲连接
      min-idle: 0
  rabbitmq:
    addresses: 127.0.0.1:5672
    port: 5672
    username: admin
    password: 123456
    publisher-confirms: true
    virtual-host: /

## 该配置节点为独立的节点，有很多同学容易将这个配置放在spring的节点下，导致配置无法被识别
mybatis:
  #注意：一定要对应mapper映射xml文件的所在路径
  mapper-locations: classpath:com/jy/mapping/*.xml
  # 注意：对应实体类的路径
  type-aliases-package: com.jy.model
  #pagehelper分页插件
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql
redisConfig:
  #单位分钟
  SSO_SESSION_EXPIRE: 30
  REDIS_USER_SESSION_KEY: REDIS_USER_SESSION
